# Generated by Django 3.1.7 on 2021-03-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
